apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: pvc-backup
  namespace: demo
spec:
  target:
    apiGroup:
    kind: PersistentVolumeClaim
    name: backup-target-pvc
    namespace: demo
  backends:
    - name: pvc-backend
      storageRef:
        namespace: demo
        name: s3-storage
      retentionPolicy:
        name: demo-retention
        namespace: demo
  sessions:
    - name: two-minutes-backup
      sessionHistoryLimit: 3
      scheduler: # CronJob specification
        schedule: "*/2 * * * *"
        successfulJobsHistoryLimit: 2
        failedJobsHistoryLimit: 2
        jobTemplate: # Comes from batch/v1 JobTemplateSpec
          backoffLimit: 0
      repositories: # volume & volumeMount strategy.
        - name: pvc-demo-s3
          backend: pvc-backend
          directory: /backup-target-pvc
          encryptionSecret:
            name: encrypt-secret # some addon may not support encryption
            namespace: demo
          deletionPolicy: WipeOut 
      addon:
        name: pvc-addon
        tasks:
          - name: logical-backup
    - name: three-minutes-backup
      sessionHistoryLimit: 3
      scheduler: # CronJob specification
        schedule: "*/3 * * * *"
        successfulJobsHistoryLimit: 2
        failedJobsHistoryLimit: 2
        jobTemplate: # Comes from batch/v1 JobTemplateSpec
          backoffLimit: 0
      repositories: # volume & volumeMount strategy.
        - name: pvc-demo-s3
          backend: pvc-backend
          directory: /backup-target-pvc
          encryptionSecret:
            name: encrypt-secret # some addon may not support encryption
            namespace: demo
          deletionPolicy: WipeOut 
      addon:
        name: pvc-addon
        tasks:
          - name: logical-backup
        jobTemplate:
          spec: 
            securityContext: 
              runAsUser: 0
