apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: demo
spec:
  containers:
  - name: busybox
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args: 
    - |
      echo "sample_data, from demo-pod" > /target/mountpath/data.txt
      sleep 3000
    volumeMounts:
    - name: my-volume
      mountPath: /target/mountpath
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: backup-target-pvc
