apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
  labels:
    app: local #for multiple pv, need to match with label [selector]
spec:
  capacity:
    storage: 4Gi
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/kubestash-test"
